version: '3'
services:
    sonar:
        build: ./sonar
        depends_on:
            - api
            - ui
            - proxy
    api:
        build:
          context: ./api
        volumes:
            - ./api:/usr/local/src/app/api
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
        command: ["main:app", "--host", "0.0.0.0", "--reload"]
    ui:
        build: ./ui
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./ui/src:/usr/local/src/app/ui/src
            - ./ui/public:/usr/local/src/app/ui/public
            - ./ui/package.json:/usr/local/src/app/ui/package.json
            - ./ui/tsconfig.json:/usr/local/src/app/ui/tsconfig.json
            - ./ui/yarn.lock:/usr/local/src/app/ui/yarn.lock
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - api
            - ui